#Real Tree Configuration

#Run in creative mode
#Usually the plugin will disable it's autoplant functionality when player/server is in creative mode
#this toggle overrides that behavior.
Creative_Mode: false

#Delay from log break to the sapling being planted (in seconds) 
Plant_Delay: 5
#How long the sapling is protected after this plugin plants it (in seconds)
#As a rule of thumb, this time should probably be longer than the Plant_Delay
Protect_Time: 10

#When true the plugin will autoplant a burning log
Replant_Burned_Tree: true

#Are we going to protect the saplings?
Protect_Saplings: true
#Should we protect the square before the sapling is spawned?
Protect_Before_Replant: false

#If these are true the the text in the variables below will be shown
Tell_User_Planting: false
Tell_User_Protected: true

#The message that is sent to the player when a sapling is added to the play queue
Being_Planted_Text: A new sapling will arrive in one moment
#The message that is sent to the player when they try to break the recently planted/protected sapling
Protected_Text: This sapling is protected for a while.

#FastGrow options
Fastgrow_Enabled: true
#Time in seconds before Fastgrow starts
Fastgrow_Basetime: 5
Fastgrow_Randomtime: 0

#Percent chance of a big tree or redwood tree
Fastgrow_BigTree: 40
Fastgrow_RedWood: 40

#Should we drop saplings if the tree can't grow?
Fastgrow_DropFailedTrees: false