name: RealTree
main: us.bangrocket.realtree.RealTree
version: 0.9
commands:
    realtree:
        description: RealTree commands
        usage: /<command>
        aliases:
        - rt
    livingforest:
        description: Supported commands from defunct LivingForest plugins
        usage: /<command>
        aliases:
        - lf
        